### ISSUE TITLE
Error on line 27, column 3 of pubspec.yaml: A package may not list itself as a dependency.

### ISSUE THREAD

**Issue by suthishan** [shah-xad/flutter_background_location#2]
Error on line 27, column 3 of pubspec.yaml: A package may not list itself as a dependency.

**Comment by shah-xad** [comment]
I'm guessing the name of your flutter project is also flutter_background_location. Please try to change that..

**Comment by suthishan** [comment]
ya you are right. i changed and working on it thanks a lot.

**Comment by shah-xad** [comment]
Ok fine its solved.. 😊
